---
include:
  # dongle
  - board: xiao_ble//zmk
    name: prospector_dongle
    shield: dongle prospector_adapter
    modules: [prospector-zmk-module]

  - board: xiao_ble//zmk
    name: xiao_reset
    shield: settings_reset

  # peripherals
  - board: nice_nano//zmk
    shield: corne_bare_left

  - board: nice_nano//zmk
    shield: corne_bare_right

  - board: nice_nano//zmk
    name: nicenano_reset
    shield: settings_reset
